name: CI/CD DevOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu          # Your EC2 username
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd devops-project

            # Ensure we have the latest code
            git reset --hard
            git pull origin main

            # Stop running containers
            docker-compose down || true

            # Rebuild images without cache
            docker-compose build --no-cache

            # Start containers
            docker-compose up -d

            # Optional: show running containers
            docker ps